apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.controller.vSphereConfigSecret }}
  namespace: {{ include "vsphere-csi.namespace" . }}
  labels:
    {{- include "vsphere-csi.labels" . | nindent 4 }}
type: Opaque
stringData:
  csi-vsphere.conf: |
    [Global]
    cluster-id = {{ .Values.vSphereConfig.global.clusterID | quote }}
    cluster-distribution = {{ .Values.vSphereConfig.global.clusterDistribution | quote }}

    [VirtualCenter {{ .Values.vSphereConfig.vcenter.server | quote }}]
    insecure-flag = {{ .Values.vSphereConfig.vcenter.insecureFlag | quote }}
    user = {{ .Values.vSphereConfig.vcenter.user | quote }}
    password = {{ .Values.vSphereConfig.vcenter.password | quote }}
    port = {{ .Values.vSphereConfig.vcenter.port | quote }}
    datacenters = {{ .Values.vSphereConfig.vcenter.datacenters | quote }}
