{{- if .Values.storageClass.enabled }}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storageClass.name }}
  annotations:
    storageclass.kubernetes.io/is-default-class: {{ .Values.storageClass.isDefault | quote }}
  labels:
    {{- include "vsphere-csi.labels" . | nindent 4 }}
provisioner: {{ .Values.csiDriver.name }}
allowVolumeExpansion: {{ .Values.storageClass.allowVolumeExpansion }}
{{- with .Values.storageClass.reclaimPolicy }}
reclaimPolicy: {{ . }}
{{- end }}
{{- with .Values.storageClass.volumeBindingMode }}
volumeBindingMode: {{ . }}
{{- end }}
{{- with .Values.storageClass.parameters }}
parameters:
  {{- toYaml . | nindent 2 }}
{{- end }}
{{- end }}
